#!/usr/bin/env python3
import yaml
from jinja2 import Environment, FileSystemLoader
import sys

def run_init():
    with open("manifest.yaml") as f:
        manifest = yaml.safe_load(f)
    env = Environment(loader=FileSystemLoader("templates/"))
    template = env.get_template("nginx.conf.j2")
    rendered = template.render(
        service_port=manifest["services"]["port"],
        nginx_port=manifest["nginx"]["port"],
        proxy_timeout=manifest["nginx"]["proxy_timeout"]
    )
    with open("nginx.conf","w") as f:
        f.write(rendered)

    template = env.get_template("docker-compose.yml.j2")
    rendered = template.render(
       service_image=manifest["services"]["image"],
       service_mode=manifest["services"]["mode"],
       service_version=manifest["services"]["version"],
       service_port=manifest["services"]["port"],
       network_name=manifest["network"]["name"],
       restart_policy=manifest["services"]["restart_policy"],
       log_volume=manifest["services"]["log_volume"],
       nginx_image=manifest["nginx"]["image"],
       nginx_port=manifest["nginx"]["port"],
       network_driver=manifest["network"]["driver_type"]
    )
    with open("docker-compose.yml","w") as f:
        f.write(rendered)
    print("Generated nginx.conf")
    print("Generated docker-compose.yml")

def run_validate():
    pass
def run_deploy():
    pass
def run_promote(mode):
    pass
def run_teardown():
    pass

command = sys.argv[1] if len(sys.argv) > 1 else ""

if command == "init":
    run_init()
elif command == "validate":
    run_validate()
elif command == "deploy":
    run_deploy()
elif command == "promote":
    run_promote(sys.argv[2])
elif command == "teardown":
    run_teardown()
else: 
    print("Usage: ./swiftdeploy [init|validate|deploy|promote|teardown]")
    sys.exit(1)
